import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'mr' | 'pa' | 'gu' | 'ta' | 'te'; 

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, namespace?: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Layout
    "nav.weather": "Agri-Weather",
    "nav.mandi": "Mandi Bhav",
    "nav.ledger": "Hisab-Kitab",
    "nav.guide": "Kheti Guide",
    "nav.dashboard": "Back to Dashboard",
    // Weather
    "weather.title": "Agri-Weather AI",
    "weather.subtitle": "Hyper-local climate & soil intelligence",
    "weather.refresh": "Refresh",
    "weather.realtime": "Real-time Environment",
    "weather.wind": "Wind",
    "weather.celsius": "Celsius",
    "weather.soilLevel": "Soil Moisture Level",
    "weather.optimalRange": "Optimal range: 40% - 60%",
    "weather.humidity": "Humidity",
    "weather.evapo": "Evapotrans.",
    "weather.rain1h": "Rain 1h",
    "weather.timezone": "Timezone",
    "weather.forecast7d": "7-Day Environmental Forecast",
    "weather.disclaimer": "Disclaimer: Weather forecasts are approximate and may occasionally vary from other sources like Google Weather due to differences in meteorological models, update frequencies, and hyper-local data points.",
    // Khatabook
    "khata.title": "Hisab-Kitab",
    "khata.subtitle": "(Agri-Ledger)",
    "khata.desc": "Professional crop expense tracking & ROI forecasting.",
    "khata.howToUse": "How to use?",
    "khata.hideGuide": "Hide Guide",
    "khata.exportPdf": "Export PDF",
    "khata.myCrops": "My Crops",
    "khata.addCycle": "Add Cycle",
    "khata.addCyclePlaceholder": "e.g. Kharif Paddy 2024",
    "khata.noCrops": "No crops added yet.",
    "khata.selectCycle": "Select a crop cycle to open its ledger.",
    "khata.totalInputCost": "Total Input Cost",
    "khata.salePrice": "Sale Price (Expected)",
    "khata.roi": "Return on Investment",
    "khata.newEntry": "New Entry",
    "khata.amount": "Amount (₹)",
    "khata.add": "Add",
    "khata.logs": "Transaction Log",
    "khata.date": "Date",
    "khata.category": "Category",
    "khata.amountDebit": "Amount Drawn (Debit)",
    "khata.emptyLog": "This ledger page is empty. Record your first expense.",
    // SOP
    "sop.title": "Interactive Kheti Guide",
    "sop.subtitle": "Smart SOP Task Timeline Tracking",
    "sop.selectCycle": "Select a Crop Cycle",
    "sop.noCrops": "No crops found. Create one in Hisab-Kitab.",
    "sop.farmOps": "Farm Operations",
    "sop.expected": "Expected: Day",
    "sop.ofCycle": "of Cycle",
    "sop.verified": "Verified",
    "sop.pending": "Pending",
    "sop.mathVerified": "Mathematically Verified",
    "sop.time": "Time",
    "sop.gps": "GPS",
    "sop.openCamera": "Open Camera to Verify",
    "sop.cancel": "Cancel",
    "sop.verify": "Verify",
    "sop.cameraDesc": "We will capture GPS coordinates & secure timestamp to cryptographically log this action.",
    // Mandi
    "mandi.title": "Mandi Bhav",
    "mandi.subtitle": "Live commodity prices based on your location",
    "mandi.searchPlaceholder": "Enter City manually...",
    "mandi.searchLocating": "Locating",
    "mandi.updateGps": "Update GPS",
    "mandi.gpsActive": "GPS Active",
    "mandi.selectState": "Select State",
    "mandi.selectDist": "Select Dist",
    "mandi.selectMandi": "Select Mandi",
    "mandi.checkPrice": "Check Price",
    "mandi.youAreHere": "You are here!",
    "mandi.viewPrices": "View Prices",
    "mandi.nearestMarkets": "Nearest Markets",
    "mandi.found": "found",
    "mandi.backToList": "Back to list",
    "mandi.away": "away",
    "mandi.expensive": "Expensive here",
    "mandi.cheaper": "Cheaper here",
    "mandi.avgPrice": "Average price",
    "mandi.nearbyComparison": "Nearby Comparison",
    "mandi.noData": "No price data available for this market.",
    "mandi.qtl": "qtl",
  },
  hi: {
    // Layout
    "nav.weather": "कृषि-मौसम",
    "nav.mandi": "मंडी भाव",
    "nav.ledger": "हिसाब-किताब",
    "nav.guide": "खेती गाइड",
    "nav.dashboard": "डैशबोर्ड पर वापस जाएं",
    // Weather
    "weather.title": "कृषि-मौसम एआई",
    "weather.subtitle": "अति-स्थानीय जलवायु और मिट्टी की जानकारी",
    "weather.refresh": "रिफ्रेश",
    "weather.realtime": "वास्तविक समय का वातावरण",
    "weather.wind": "हवा",
    "weather.celsius": "सेल्सियस",
    "weather.soilLevel": "मिट्टी की नमी का स्तर",
    "weather.optimalRange": "इष्टतम सीमा: 40% - 60%",
    "weather.humidity": "नमी",
    "weather.evapo": "वाष्पीकरण",
    "weather.rain1h": "बारिश १ घंटा",
    "weather.timezone": "समय क्षेत्र",
    "weather.forecast7d": "7-दिवसीय पर्यावरण पूर्वानुमान",
    "weather.disclaimer": "अस्वीकरण: मौसम का पूर्वानुमान अनुमानित है और मौसम संबंधी मॉडल आदि अंतर के कारण गूगल वेदर जैसे अन्य स्रोतों से कभी-कभी भिन्न हो सकता है।",
    // Khatabook
    "khata.title": "हिसाब-किताब",
    "khata.subtitle": "(कृषि खाता)",
    "khata.desc": "प्रोफेशनल फसल खर्च ट्रैकिंग और ROI पूर्वानुमान.",
    "khata.howToUse": "कैसे उपयोग करें?",
    "khata.hideGuide": "गाइड छुपाएं",
    "khata.exportPdf": "PDF डाउनलोड",
    "khata.myCrops": "मेरी फसलें",
    "khata.addCycle": "फसल जोड़ें",
    "khata.addCyclePlaceholder": "जैसे: खरीफ धान 2024",
    "khata.noCrops": "कोई फसल नहीं जोड़ी गई है।",
    "khata.selectCycle": "खाता खोलने के लिए फसल चुनें।",
    "khata.totalInputCost": "कुल लागत",
    "khata.salePrice": "बिक्री मूल्य (अपेक्षित)",
    "khata.roi": "निवेश पर रिटर्न",
    "khata.newEntry": "नई प्रविष्टि",
    "khata.amount": "रकम (₹)",
    "khata.add": "जोड़ें",
    "khata.logs": "लेन-देन इतिहास",
    "khata.date": "तारीख़",
    "khata.category": "श्रेणी",
    "khata.amountDebit": "निकाली गई राशि",
    "khata.emptyLog": "यह खाता खाली है। अपना पहला खर्च दर्ज करें।",
    // SOP
    "sop.title": "इंटरेक्टिव खेती गाइड",
    "sop.subtitle": "स्मार्ट SOP टास्क टाइमलाइन ट्रैकिंग",
    "sop.selectCycle": "फसल चुनें",
    "sop.noCrops": "कोई फसल नहीं मिली। हिसाब-किताब में एक बनाएं।",
    "sop.farmOps": "कृषि कार्य",
    "sop.expected": "अपेक्षित: दिन",
    "sop.ofCycle": "चक्र का",
    "sop.verified": "सत्यापित",
    "sop.pending": "लंबित",
    "sop.mathVerified": "गणितीय रूप से सत्यापित",
    "sop.time": "समय",
    "sop.gps": "GPS",
    "sop.openCamera": "कैमरा खोलें और सत्यापित करें",
    "sop.cancel": "रद्द करें",
    "sop.verify": "सत्यापित करें",
    "sop.cameraDesc": "हम इस कार्रवाई को सुरक्षित रूप से लॉग करने के लिए आपके GPS निर्देशांक और सुरक्षित समय कैप्चर करेंगे।",
    // Mandi
    "mandi.title": "मंडी भाव",
    "mandi.subtitle": "आपकी लोकेशन के अनुसार ताज़ा फसल की कीमतें",
    "mandi.searchPlaceholder": "शहर का नाम भरें...",
    "mandi.searchLocating": "खोज रहे हैं",
    "mandi.updateGps": "GPS अपडेट करें",
    "mandi.gpsActive": "GPS सक्रिय है",
    "mandi.selectState": "राज्य चुनें",
    "mandi.selectDist": "ज़िला चुनें",
    "mandi.selectMandi": "मंडी चुनें",
    "mandi.checkPrice": "भाव देखें",
    "mandi.youAreHere": "आप यहाँ हैं!",
    "mandi.viewPrices": "भाव देखें",
    "mandi.nearestMarkets": "नज़दीकी मंडियां",
    "mandi.found": "मिली",
    "mandi.backToList": "सूची पर वापस जाएं",
    "mandi.away": "दूर",
    "mandi.expensive": "यहाँ महँगा है",
    "mandi.cheaper": "यहाँ सस्ता है",
    "mandi.avgPrice": "औसत मूल्य",
    "mandi.nearbyComparison": "आसपास की मंडियों से तुलना",
    "mandi.noData": "इस मंडी के लिए कोई डेटा उपलब्ध नहीं है।",
    "mandi.qtl": "क्विंटल",
  },
  mr: {
    // Marathi Translations
    "nav.weather": "कृषी-हवामान",
    "nav.mandi": "मंडी भाव",
    "nav.ledger": "हिशोब-किताब",
    "nav.guide": "शेती मार्गदर्शक",
    "nav.dashboard": "डॅशबोर्डवर परत जा",
    "weather.title": "कृषी-हवामान AI",
    "weather.subtitle": "स्थानिक हवामान आणि मातीची पातळी",
    "weather.refresh": "रिफ्रेश",
    "weather.realtime": "थेट वातावरण",
    "weather.wind": "वारा",
    "weather.celsius": "सेल्सिअस",
    "weather.soilLevel": "मातीची ओलावा पातळी",
    "weather.optimalRange": "इष्टतम श्रेणी: ४०% - ६०%",
    "weather.humidity": "आर्द्रता",
    "weather.evapo": "बाष्पीभवन",
    "weather.rain1h": "पाऊस १ तास",
    "weather.timezone": "वेळ क्षेत्र",
    "weather.forecast7d": "७-दिवसीय हवामान अंदाज",
    "weather.disclaimer": "अस्वीकरण: हवामान अंदाज अंदाजे आहेत.",
    "khata.title": "हिशोब-किताब",
    "khata.subtitle": "(कृषी खाते)",
    "khata.desc": "पीक खर्च ट्रॅकिंग आणि ROI अंदाज.",
    "khata.howToUse": "कसे वापरावे?",
    "khata.hideGuide": "मार्गदर्शक लपवा",
    "khata.exportPdf": "PDF डाउनलोड",
    "khata.myCrops": "माझी पिके",
    "khata.addCycle": "सायकल जोडा",
    "khata.addCyclePlaceholder": "उदा: खरीप भात २०२४",
    "khata.noCrops": "अद्याप कोणतीही पिके जोडलेली नाहीत.",
    "khata.selectCycle": "खाते उघडण्यासाठी पीक चक्र निवडा.",
    "khata.totalInputCost": "एकूण खर्च",
    "khata.salePrice": "विक्री किंमत (अपेक्षित)",
    "khata.roi": "गुंतवणुकीवर परतावा",
    "khata.newEntry": "नवीन नोंद",
    "khata.amount": "रक्कम (₹)",
    "khata.add": "जोडा",
    "khata.logs": "व्यवहार नोंद",
    "khata.date": "तारीख",
    "khata.category": "श्रेणी",
    "khata.amountDebit": "काढलेली रक्कम",
    "khata.emptyLog": "हे खाते रिक्त आहे. तुमचा पहिला खर्च नोंदवा.",
    "sop.title": "परस्परसंवादी शेती मार्गदर्शक",
    "sop.subtitle": "स्मार्ट SOP टास्क टाइमलाइन ट्रॅकिंग",
    "sop.selectCycle": "पीक चक्र निवडा",
    "sop.noCrops": "कोणतीही पिके आढळली नाहीत. हिशोब-किताबमध्ये एक तयार करा.",
    "sop.farmOps": "शेतीची कामे",
    "sop.expected": "अपेक्षित: दिवस",
    "sop.ofCycle": "चक्राचा",
    "sop.verified": "सत्यापित",
    "sop.pending": "प्रलंबित",
    "sop.mathVerified": "गणितीय दृष्ट्या सत्यापित",
    "sop.time": "वेळ",
    "sop.gps": "GPS",
    "sop.openCamera": "कॅमेरा उघडा आणि सत्यापित करा",
    "sop.cancel": "रद्द करा",
    "sop.verify": "सत्यापित करा",
    "sop.cameraDesc": "येथे GPS समन्वय आणि सुरक्षित वेळ कॅप्चर केले जातील.",
    "mandi.title": "मंडी भाव",
    "mandi.subtitle": "तुमच्या स्थानावर आधारित थेट कमोडिटी किमती",
    "mandi.searchPlaceholder": "शहर व्यक्तिचलितपणे प्रविष्ट करा...",
    "mandi.searchLocating": "शोधत आहे",
    "mandi.updateGps": "GPS अपडेट करा",
    "mandi.gpsActive": "GPS सक्रिय",
    "mandi.selectState": "राज्य निवडा",
    "mandi.selectDist": "जिल्हा निवडा",
    "mandi.selectMandi": "मंडी निवडा",
    "mandi.checkPrice": "किंमत तपासा",
    "mandi.youAreHere": "तू इथे आहेस!",
    "mandi.viewPrices": "किमती पहा",
    "mandi.nearestMarkets": "जवळच्या बाजारपेठा",
    "mandi.found": "सापडली",
    "mandi.backToList": "यादीवर परत",
    "mandi.away": "दूर",
    "mandi.expensive": "येथे महाग",
    "mandi.cheaper": "येथे स्वस्त",
    "mandi.avgPrice": "सरासरी किंमत",
    "mandi.nearbyComparison": "जवळपासची तुलना",
    "mandi.noData": "या बाजारासाठी कोणतीही किंमत डेटा उपलब्ध नाही.",
    "mandi.qtl": "क्विंटल",
  },
  pa: {
    // Punjabi
    "nav.weather": "ਖੇਤੀ-ਮੌਸਮ",
    "nav.mandi": "ਮੰਡੀ ਭਾਅ",
    "nav.ledger": "ਹਿਸਾਬ-ਕਿਤਾਬ",
    "nav.guide": "ਖੇਤੀ ਗਾਈਡ",
    "nav.dashboard": "ਡੈਸ਼ਬੋਰਡ 'ਤੇ ਵਾਪਸ ਜਾਓ",
    "weather.title": "ਖੇਤੀ-ਮੌਸਮ ਏਆਈ",
    "weather.subtitle": "ਸਥਾਨਕ ਜਲਵਾਯੂ ਅਤੇ ਮਿੱਟੀ ਦੀ ਜਾਣਕਾਰੀ",
    "weather.refresh": "ਤਾਜ਼ਾ ਕਰੋ",
    "weather.realtime": "ਰੀਅਲ-ਟਾਈਮ ਵਾਤਾਵਰਣ",
    "weather.wind": "ਹਵਾ",
    "weather.celsius": "ਸੈਲਸੀਅਸ",
    "weather.soilLevel": "ਮਿੱਟੀ ਦੀ ਨਮੀ",
    "weather.optimalRange": "ਸਰਵੋਤਮ ਰੇਂਜ: 40% - 60%",
    "weather.humidity": "ਨਮੀ",
    "weather.evapo": "ਵਾਸ਼ਪੀਕਰਨ",
    "weather.rain1h": "ਮੀਂਹ 1 ਘੰਟਾ",
    "weather.timezone": "ਸਮਾਂ ਖੇਤਰ",
    "weather.forecast7d": "7-ਦਿਨ ਮੌਸਮ ਦੀ ਭਵਿੱਖਬਾਣੀ",
    "weather.disclaimer": "ਬੇਦਾਅਵਾ: ਮੌਸਮ ਦੀ ਭਵਿੱਖਬਾਣੀ ਅੰਦਾਜ਼ਨ ਹੈ।",
    "khata.title": "ਹਿਸਾਬ-ਕਿਤਾਬ",
    "khata.subtitle": "(ਖੇਤੀ ਖਾਤਾ)",
    "khata.desc": "ਪੇਸ਼ੇਵਰ ਫਸਲ ਖਰਚੇ ਦੀ ਟਰੈਕਿੰਗ ਅਤੇ ROI",
    "khata.howToUse": "ਕਿਵੇਂ ਵਰਤਣਾ ਹੈ?",
    "khata.hideGuide": "ਗਾਈਡ ਛੁਪਾਓ",
    "khata.exportPdf": "PDF ਡਾਊਨਲੋਡ",
    "khata.myCrops": "ਮੇਰੀਆਂ ਫਸਲਾਂ",
    "khata.addCycle": "ਫਸਲ ਸ਼ਾਮਲ ਕਰੋ",
    "khata.addCyclePlaceholder": "ਖਰੀਫ ਝੋਨਾ 2024",
    "khata.noCrops": "ਕੋਈ ਫਸਲਾਂ ਨਹੀਂ ਸ਼ਾਮਲ ਕੀਤੀਆਂ ਗਈਆਂ.",
    "khata.selectCycle": "ਖਾਤਾ ਖੋਲ੍ਹਣ ਲਈ ਫਸਲ ਚੁਣੋ.",
    "khata.totalInputCost": "ਕੁੱਲ ਲਾਗਤ",
    "khata.salePrice": "ਵਿਕਰੀ ਕੀਮਤ (ਉਮੀਦ)",
    "khata.roi": "ਨਿਵੇਸ਼ 'ਤੇ ਵਾਪਸੀ",
    "khata.newEntry": "ਨਵੀਂ ਐਂਟਰੀ",
    "khata.amount": "ਰਕਮ (₹)",
    "khata.add": "ਸ਼ਾਮਲ ਕਰੋ",
    "khata.logs": "ਲੈਣ-ਦੇਣ ਲੌਗ",
    "khata.date": "ਤਾਰੀਖ",
    "khata.category": "ਸ਼੍ਰੇਣੀ",
    "khata.amountDebit": "ਕੱਢੀ ਗਈ ਰਕਮ",
    "khata.emptyLog": "ਇਹ ਖਾਤਾ ਖਾਲੀ ਹੈ.",
    "sop.title": "ਇੰਟਰਐਕਟਿਵ ਖੇਤੀ ਗਾਈਡ",
    "sop.subtitle": "ਸਮਾਰਟ SOP ਕਾਰਜ ਟਰੈਕਿੰਗ",
    "sop.selectCycle": "ਫਸਲ ਚੁਣੋ",
    "sop.noCrops": "ਕੋਈ ਫਸਲਾਂ ਨਹੀਂ ਮਿਲੀਆਂ. ਹਿਸਾਬ-ਕਿਤਾਬ ਵਿੱਚ ਇੱਕ ਬਣਾਓ.",
    "sop.farmOps": "ਖੇਤ ਦੇ ਕੰਮ",
    "sop.expected": "ਉਮੀਦ: ਦਿਨ",
    "sop.ofCycle": "ਚੱਕਰ ਦਾ",
    "sop.verified": "ਪ੍ਰਮਾਣਿਤ",
    "sop.pending": "ਬਕਾਇਆ",
    "sop.mathVerified": "ਗਣਿਤਿਕ ਤੌਰ ਤੇ ਪ੍ਰਮਾਣਿਤ",
    "sop.time": "ਸਮਾਂ",
    "sop.gps": "GPS",
    "sop.openCamera": "ਕੈਮਰਾ ਖੋਲ੍ਹੋ",
    "sop.cancel": "ਰੱਦ ਕਰੋ",
    "sop.verify": "ਪ੍ਰਮਾਣਿਤ ਕਰੋ",
    "sop.cameraDesc": "ਅਸੀਂ GPS ਕੋਆਰਡੀਨੇਟ ਅਤੇ ਸੁਰੱਖਿਅਤ ਸਮਾਂ ਕੈਪਚਰ ਕਰਾਂਗੇ.",
    "mandi.title": "ਮੰਡੀ ਭਾਅ",
    "mandi.subtitle": "ਤੁਹਾਡੇ ਸਥਾਨ 'ਤੇ ਅਧਾਰਤ ਲਾਈਵ ਕੀਮਤਾਂ",
    "mandi.searchPlaceholder": "ਸ਼ਹਿਰ ਦਾ ਨਾਮ ਦਾਖਲ ਕਰੋ...",
    "mandi.searchLocating": "ਲੱਭ ਰਿਹਾ ਹੈ",
    "mandi.updateGps": "GPS ਅੱਪਡੇਟ ਕਰੋ",
    "mandi.gpsActive": "GPS ਸਰਗਰਮ",
    "mandi.selectState": "ਰਾਜ ਚੁਣੋ",
    "mandi.selectDist": "ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ",
    "mandi.selectMandi": "ਮੰਡੀ ਚੁਣੋ",
    "mandi.checkPrice": "ਕੀਮਤ ਚੈੱਕ ਕਰੋ",
    "mandi.youAreHere": "ਤੁਸੀਂ ਇੱਥੇ ਹੋ!",
    "mandi.viewPrices": "ਕੀਮਤਾਂ ਦੇਖੋ",
    "mandi.nearestMarkets": "ਨਜ਼ਦੀਕੀ ਮੰਡੀਆਂ",
    "mandi.found": "ਮਿਲਿਆ",
    "mandi.backToList": "ਸੂਚੀ ਤੇ ਵਾਪਸ",
    "mandi.away": "ਦੂਰ",
    "mandi.expensive": "ਇੱਥੇ ਮਹਿੰਗਾ",
    "mandi.cheaper": "ਇੱਥੇ ਸਸਤਾ",
    "mandi.avgPrice": "ਔਸਤ ਕੀਮਤ",
    "mandi.nearbyComparison": "ਨੇੜਲੀ ਤੁਲਨਾ",
    "mandi.noData": "ਕੋਈ ਡਾਟਾ ਉਪਲਬਧ ਨਹੀਂ ਹੈ.",
    "mandi.qtl": "ਕੁਇੰਟਲ",
  },
  gu: {
    // Gujarati
    "nav.weather": "કૃષિ-હવામાન",
    "nav.mandi": "મંડી ભાવ",
    "nav.ledger": "હિસાબ-કિતાબ",
    "nav.guide": "ખેતી માર્ગદર્શિકા",
    "nav.dashboard": "ડેશબોર્ડ પર પાછા",
    "weather.title": "કૃષિ-હવામાન AI",
    "weather.subtitle": "સ્થાનિક આબોહવા અને જમીન માહિતી",
    "weather.refresh": "રિફ્રેશ",
    "weather.realtime": "લાઇવ પર્યાવરણ",
    "weather.wind": "પવન",
    "weather.celsius": "સેલ્સિયસ",
    "weather.soilLevel": "જમીનનો ભેજ",
    "weather.optimalRange": "શ્રેષ્ઠ શ્રેણી: 40% - 60%",
    "weather.humidity": "ભેજ",
    "weather.evapo": "બાષ્પીભવન",
    "weather.rain1h": "વરસાદ 1 કલાક",
    "weather.timezone": "ટાઈમઝોન",
    "weather.forecast7d": "7-દિવસીય હવામાનની આગાહી",
    "weather.disclaimer": "અસ્વીકરણ: હવામાનની આગાહી અંદાજિત છે.",
    "khata.title": "હિસાબ-કિતાબ",
    "khata.subtitle": "(કૃષિ ખાતું)",
    "khata.desc": "પાક ખર્ચ ટ્રેકિંગ અને ROI",
    "khata.howToUse": "કેવી રીતે વાપરવું?",
    "khata.hideGuide": "માર્ગદર્શિકા છુપાવો",
    "khata.exportPdf": "PDF ડાઉનલોડ",
    "khata.myCrops": "મારા પાક",
    "khata.addCycle": "પાક ઉમેરો",
    "khata.addCyclePlaceholder": "દા.ત. ખરીફ ડાંગર 2024",
    "khata.noCrops": "હજુ સુધી કોઈ પાક ઉમેર્યા નથી.",
    "khata.selectCycle": "ખાતું ખોલવા માટે પાક પસંદ કરો.",
    "khata.totalInputCost": "કુલ ખર્ચ",
    "khata.salePrice": "વેચાણ કિંમત (અપેક્ષિત)",
    "khata.roi": "રોકાણ પર વળતર",
    "khata.newEntry": "નવી એન્ટ્રી",
    "khata.amount": "રકમ (₹)",
    "khata.add": "ઉમેરો",
    "khata.logs": "વ્યવહાર લોગ",
    "khata.date": "તારીખ",
    "khata.category": "શ્રેણી",
    "khata.amountDebit": "ઉપાડેલી રકમ",
    "khata.emptyLog": "આ ખાતું ખાલી છે.",
    "sop.title": "ઇન્ટરેક્ટિવ ખેતી માર્ગદર્શિકા",
    "sop.subtitle": "સ્માર્ટ SOP કાર્ય ટ્રેકિંગ",
    "sop.selectCycle": "પાક પસંદ કરો",
    "sop.noCrops": "કોઈ પાક મળ્યા નથી.",
    "sop.farmOps": "ખેતરના કામો",
    "sop.expected": "અપેક્ષિત: દિવસ",
    "sop.ofCycle": "ચક્રનો",
    "sop.verified": "ચકાસાયેલ",
    "sop.pending": "બાકી",
    "sop.mathVerified": "ગાણિતિક રીતે ચકાસાયેલ",
    "sop.time": "સમય",
    "sop.gps": "GPS",
    "sop.openCamera": "કેમેરા ખોલો",
    "sop.cancel": "રદ કરો",
    "sop.verify": "ચકાસો",
    "sop.cameraDesc": "GPS અને સમય કેપ્ચર કરવામાં આવશે.",
    "mandi.title": "મંડી ભાવ",
    "mandi.subtitle": "તમારા સ્થાન પર આધારિત જીવંત ભાવો",
    "mandi.searchPlaceholder": "શહેર દાખલ કરો...",
    "mandi.searchLocating": "શોધી રહ્યું છે",
    "mandi.updateGps": "GPS અપડેટ",
    "mandi.gpsActive": "GPS સક્રિય",
    "mandi.selectState": "રાજ્ય પસંદ કરો",
    "mandi.selectDist": "જિલ્લો પસંદ કરો",
    "mandi.selectMandi": "મંડી પસંદ કરો",
    "mandi.checkPrice": "કિંમત તપાસો",
    "mandi.youAreHere": "તમે અહીં છો!",
    "mandi.viewPrices": "કિંમતો જુઓ",
    "mandi.nearestMarkets": "નજીકના બજારો",
    "mandi.found": "મળ્યું",
    "mandi.backToList": "યાદી પર પાછા",
    "mandi.away": "દૂર",
    "mandi.expensive": "અહીં મોંઘુ",
    "mandi.cheaper": "અહીં સસ્તું",
    "mandi.avgPrice": "સરેરાશ કિંમત",
    "mandi.nearbyComparison": "નજીકની સરખામણી",
    "mandi.noData": "કોઈ ડેટા ઉપલબ્ધ નથી.",
    "mandi.qtl": "ક્વિન્ટલ",
  },
  ta: {
    // Tamil
    "nav.weather": "விவசாய வானிலை",
    "nav.mandi": "மண்டி விலை",
    "nav.ledger": "கணக்கு புத்தகம்",
    "nav.guide": "விவசாய வழிகாட்டி",
    "nav.dashboard": "முகப்புக்கு திரும்பவும்",
    "weather.title": "விவசாய வானிலை AI",
    "weather.subtitle": "உள்ளூர் காலநிலை மற்றும் மண்",
    "weather.refresh": "புதுப்பி",
    "weather.realtime": "நேரலை சூழல்",
    "weather.wind": "காற்று",
    "weather.celsius": "செல்சியஸ்",
    "weather.soilLevel": "மண் ஈரப்பதம்",
    "weather.optimalRange": "உகந்த வரம்பு: 40% - 60%",
    "weather.humidity": "ஈரப்பதம்",
    "weather.evapo": "நீராவியாதல்",
    "weather.rain1h": "மழை 1 மணிநேரம்",
    "weather.timezone": "நேர மண்டலம்",
    "weather.forecast7d": "7 நாள் வானிலை அறிக்கை",
    "weather.disclaimer": "மறுப்பு: வானிலை அறிக்கை தோராயமானது.",
    "khata.title": "கணக்கு புத்தகம்",
    "khata.subtitle": "(விவசாய கணக்கு)",
    "khata.desc": "பயிர் செலவு கண்காணிப்பு மற்றும் ROI.",
    "khata.howToUse": "எப்படி பயன்படுத்துவது?",
    "khata.hideGuide": "வழிகாட்டியை மறை",
    "khata.exportPdf": "PDF பதிவிறக்கு",
    "khata.myCrops": "என் பயிர்கள்",
    "khata.addCycle": "பயிர் சேர்",
    "khata.addCyclePlaceholder": "உதாரணம்: குறுவை 2024",
    "khata.noCrops": "பயிர்கள் சேர்க்கப்படவில்லை.",
    "khata.selectCycle": "கணக்கை திறக்க பயிரை தேர்ந்தெடுக்கவும்.",
    "khata.totalInputCost": "மொத்த செலவு",
    "khata.salePrice": "விற்பனை விலை (எதிர்பார்க்கப்படும்)",
    "khata.roi": "முதலீட்டின் மீதான வருவாய்",
    "khata.newEntry": "புதிய பதிவு",
    "khata.amount": "தொகை (₹)",
    "khata.add": "சேர்",
    "khata.logs": "பரிவர்த்தனை பதிவு",
    "khata.date": "தேதி",
    "khata.category": "வகை",
    "khata.amountDebit": "எடுக்கப்பட்ட தொகை",
    "khata.emptyLog": "கணக்கு காலியாக உள்ளது.",
    "sop.title": "ஊடாடும் விவசாய வழிகாட்டி",
    "sop.subtitle": "SOP பணி கண்காணிப்பு",
    "sop.selectCycle": "பயிரை தேர்ந்தெடுக்கவும்",
    "sop.noCrops": "பயிர்கள் இல்லை.",
    "sop.farmOps": "பண்ணை பணிகள்",
    "sop.expected": "எதிர்பார்க்கப்படும் நாள்:",
    "sop.ofCycle": "சுழற்சி",
    "sop.verified": "சரிபார்க்கப்பட்டது",
    "sop.pending": "நிலுவை",
    "sop.mathVerified": "கணிதப்படி சரிபார்க்கப்பட்டது",
    "sop.time": "நேரம்",
    "sop.gps": "GPS",
    "sop.openCamera": "கேமராவை திறக்கவும்",
    "sop.cancel": "ரத்துசெய்",
    "sop.verify": "சரிபார்",
    "sop.cameraDesc": "GPS மற்றும் நேரம் பதிவு செய்யப்படும்.",
    "mandi.title": "மண்டி விலை",
    "mandi.subtitle": "நேரலை கமாடிட்டி விலைகள்",
    "mandi.searchPlaceholder": "நகரத்தை உள்ளிடவும்...",
    "mandi.searchLocating": "தேடுகிறது",
    "mandi.updateGps": "GPS புதுப்பி",
    "mandi.gpsActive": "GPS செயலில் உள்ளது",
    "mandi.selectState": "மாநிலம்",
    "mandi.selectDist": "மாவட்டம்",
    "mandi.selectMandi": "மண்டி",
    "mandi.checkPrice": "விலையை சரிபார்",
    "mandi.youAreHere": "நீங்கள் இங்கே இருக்கிறீர்கள்!",
    "mandi.viewPrices": "விலைகளை காண்",
    "mandi.nearestMarkets": "அருகிலுள்ள சந்தைகள்",
    "mandi.found": "கிடைத்தது",
    "mandi.backToList": "பட்டியலுக்கு செல்",
    "mandi.away": "தொலைவு",
    "mandi.expensive": "இங்கு விலை அதிகம்",
    "mandi.cheaper": "இங்கு விலை குறைவு",
    "mandi.avgPrice": "சராசரி விலை",
    "mandi.nearbyComparison": "அருகிலுள்ள ஒப்பீடு",
    "mandi.noData": "தரவு கிடைக்கவில்லை.",
    "mandi.qtl": "குவிண்டால்",
  },
  te: {
    // Telugu
    "nav.weather": "వ్యవసాయ వాతావరణం",
    "nav.mandi": "మండి ధరలు",
    "nav.ledger": "ఖాతా పుస్తకం",
    "nav.guide": "వ్యవసాయ గైడ్",
    "nav.dashboard": "డ్యాష్‌బోర్డ్‌కు వెనుకకు",
    "weather.title": "వ్యవసాయ వాతావరణం AI",
    "weather.subtitle": "స్థానిక వాతావరణం మరియు నేల",
    "weather.refresh": "రిఫ్రెష్",
    "weather.realtime": "లైవ్ వాతావరణం",
    "weather.wind": "గాలి",
    "weather.celsius": "సెల్సియస్",
    "weather.soilLevel": "నేల తేమ",
    "weather.optimalRange": "ఆప్టిమల్ రేంజ్: 40% - 60%",
    "weather.humidity": "తేమ",
    "weather.evapo": "బాష్పీభవనం",
    "weather.rain1h": "వర్షం 1 గంట",
    "weather.timezone": "టైమ్‌జోన్",
    "weather.forecast7d": "7-రోజుల వాతావరణం",
    "weather.disclaimer": "నిరాకరణ: వాతావరణం అంచనా మాత్రమే.",
    "khata.title": "ఖాతా పుస్తకం",
    "khata.subtitle": "(వ్యవసాయ ఖాతా)",
    "khata.desc": "ఖర్చు ట్రాకింగ్ మరియు ROI.",
    "khata.howToUse": "ఎలా వాడాలి?",
    "khata.hideGuide": "గైడ్ దాచండి",
    "khata.exportPdf": "PDF డౌన్‌లోడ్",
    "khata.myCrops": "నా పంటలు",
    "khata.addCycle": "పంట జోడించండి",
    "khata.addCyclePlaceholder": "ఉదాహరణ: ఖరీఫ్ వరి 2024",
    "khata.noCrops": "పంటలు లేవు.",
    "khata.selectCycle": "ఖాతా తెరవడానికి పంటను ఎంచుకోండి.",
    "khata.totalInputCost": "మొత్తం ఖర్చు",
    "khata.salePrice": "విక్రయ ధర (ఆశించిన)",
    "khata.roi": "పెట్టుబడిపై రాబడి (ROI)",
    "khata.newEntry": "కొత్త ఎంట్రీ",
    "khata.amount": "మొత్తం (₹)",
    "khata.add": "జోడించండి",
    "khata.logs": "లావాదేవీల చిట్టా",
    "khata.date": "తేదీ",
    "khata.category": "వర్గం",
    "khata.amountDebit": "తీసుకున్న మొత్తం",
    "khata.emptyLog": "ఈ ఖాతా ఖాళీగా ఉంది.",
    "sop.title": "వ్యవసాయ గైడ్",
    "sop.subtitle": "స్మార్ట్ SOP టాస్క్ ట్రాకింగ్",
    "sop.selectCycle": "పంటను ఎంచుకోండి",
    "sop.noCrops": "పంటలు కనుగొనబడలేదు.",
    "sop.farmOps": "పొలం పనులు",
    "sop.expected": "ఆశించిన రోజు:",
    "sop.ofCycle": "సైకిల్",
    "sop.verified": "ధృవీకరించబడింది",
    "sop.pending": "పెండింగ్",
    "sop.mathVerified": "ధృవీకరించబడింది",
    "sop.time": "సమయం",
    "sop.gps": "GPS",
    "sop.openCamera": "కెమెరా తెరవండి",
    "sop.cancel": "రద్దు",
    "sop.verify": "ధృవీకరించండి",
    "sop.cameraDesc": "GPS మరియు సమయం సంగ్రహించబడతాయి.",
    "mandi.title": "మండి ధరలు",
    "mandi.subtitle": "లైవ్ ధరలు",
    "mandi.searchPlaceholder": "నగరాన్ని నమోదు చేయండి...",
    "mandi.searchLocating": "వెతుకుతోంది",
    "mandi.updateGps": "GPS నవీకరించు",
    "mandi.gpsActive": "GPS యాక్టివ్",
    "mandi.selectState": "రాష్ట్రం ఎంచుకోండి",
    "mandi.selectDist": "జిల్లా ఎంచుకోండి",
    "mandi.selectMandi": "మండి ఎంచుకోండి",
    "mandi.checkPrice": "ధర చూడండి",
    "mandi.youAreHere": "మీరు ఇక్కడే ఉన్నారు!",
    "mandi.viewPrices": "ధరలు చూడండి",
    "mandi.nearestMarkets": "సమీప మార్కెట్లు",
    "mandi.found": "దొరికాయి",
    "mandi.backToList": "జాబితాకు వెనుకకు",
    "mandi.away": "దూరం",
    "mandi.expensive": "ఖరీదైనది",
    "mandi.cheaper": "చవకైనది",
    "mandi.avgPrice": "సగటు ధర",
    "mandi.nearbyComparison": "సమీప పోలిక",
    "mandi.noData": "డేటా లేదు.",
    "mandi.qtl": "క్వింటాల్",
  }
};

const LanguageContext = createContext<LanguageContextProps>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('kisanLanguage');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('kisanLanguage', language);
  }, [language]);

  const t = (key: string, namespace?: string) => {
    const defaultVal = translations['en'][key] || key;
    return translations[language]?.[key] || defaultVal;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
